### ISSUE TITLE
Crash when using vars that are not strings

### ISSUE THREAD

**Issue by Demivan** [pulumi/pulumi-nomad#389]
### Describe what happened

Pulumi crashes when sending variables of types other than strings to the job.

### Sample program

```ts
import * as nomad from "@pulumi/nomad";

const job = new nomad.Job("nomad-job", {
    hcl2: {
        vars: {
            port: 8000
        }
    },

    jobspec: `
    variable "port" {
        type = number
    }

    job "nomad-job" {
        group "nomad-job" {
            count = 1

            network {
                port "http" {
                    static = var.port
                }
            }
        }
    }
    `
});

```

### Log output

```
❯ pulumi preview
Previewing update (dev)

     Type                 Name         Plan       Info
 +   pulumi:pulumi:Stack  project-dev  create     1 error; 47 messages
 +   └─ nomad:index:Job   nomad-job    create     1 error

Diagnostics:
  pulumi:pulumi:Stack (project-dev):
    panic: interface conversion: interface {} is int, not string [recovered]
    	panic: interface conversion: interface {} is int, not string
    goroutine 28 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).recoverOnTypeError(0x41a865?, {0xc0004aa3c0?, 0x4700f2?}, {0x12e2a40, 0xc000447200})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:218 +0x145
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...].func1()
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:201 +0x64
    panic({0x12e2a40?, 0xc000447200?})
    	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:770 +0x132
    github.com/hashicorp/terraform-provider-nomad/nomad.parseHCL2JobParserConfig({0x1219140?, 0xc000794738?})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-provider-nomad@v1.4.21-0.20240531082318-be273db9f7a8/nomad/resource_job.go:907 +0x288
    github.com/hashicorp/terraform-provider-nomad/nomad.parseJobParserConfig({0x1704840, 0xc000577300})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-provider-nomad@v1.4.21-0.20240531082318-be273db9f7a8/nomad/resource_job.go:863 +0xa7
    github.com/hashicorp/terraform-provider-nomad/nomad.jobspecEqual({0x12b9be0?, 0xc00029bc78?}, {0x0, 0x0}, {0xc00047c120, 0x10b}, {0x1704840?, 0xc000577300?})
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-provider-nomad@v1.4.21-0.20240531082318-be273db9f7a8/nomad/resource_job.go:1079 +0x58
    github.com/hashicorp/terraform-provider-nomad/nomad.jobspecDiffSuppress({0x14c1754?, 0xc000446f60?}, {0x0?, 0xc000022140?}, {0xc00047c120?, 0x171c4d0?}, 0xc000577300?)
    	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-provider-nomad@v1.4.21-0.20240531082318-be273db9f7a8/nomad/resource_job.go:1069 +0x2c
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.diff(0xc00048ad50, {0x1713f88, 0xc000638ba0}, {0x14c1754, 0x7}, 0xc000022140, 0xc000577280, {0x171c4d0, 0xc000577300}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/schema.go:1143 +0x39d
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00048ad50, {0x1713f88, 0xc000638ba0}, 0xc00029a750, 0xc0000d4aa0, 0x155d6c0, {0x13ce8a0, 0xc000280680}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/schema.go:678 +0x332
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x1713f88?, 0xc000638ba0?}, 0xc00029a750, 0xc00029a680?, {0x13ce8a0?, 0xc000280680?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20240520223432-0c0bf0d65f10/helper/schema/resource.go:962 +0xdb
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0xc00048ae70?, {0x146f760?, 0xc0003d9400?, 0x740b6c4d35b8?}}, {0x1713f88, 0xc000638ba0}, 0x10?, 0xc00067dc00, 0xc0006fd1d8?, 0xc0000d4aa0, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfshim/sdk-v2/provider_diff.go:123 +0x8fc
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc0001145a0?, {0x0?, 0xc000581e10?, 0xc0006fd308?}}, {0x1713f88, 0xc000638ba0}, {0x14c44bf, 0x9}, {0x0, 0x0}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfshim/sdk-v2/provider_diff.go:75 +0x411
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create.func1()
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:1145 +0x12d
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.callWithRecover[...]({0xc0004aa3c0?, 0xc0000d4aa0?}, 0x0?, 0x171c250?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:206 +0x82
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc0007a5988, {0x1713f88?, 0xc000403e00?}, 0xc0003966e0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.84.0/pkg/tfbridge/provider.go:1144 +0x778
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1713f88?, 0xc000403e00?}, {0x13eca80?, 0xc0003966e0?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.118.0/proto/go/provider_grpc.pb.go:651 +0xcb
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1713f88, 0xc00022d860}, {0x13eca80, 0xc0003966e0}, 0xc0003dc720, 0xc0003309c0)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3db
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x1491e40, 0xc0007a5988}, {0x1713f88, 0xc00022d860}, 0xc00032e580, 0xc0005f1e80)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.118.0/proto/go/provider_grpc.pb.go:653 +0x143
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005f4400, {0x1713f88, 0xc00022d7d0}, {0x171e5e0, 0xc0001f0f00}, 0xc000028000, 0xc000273e90, 0x2178538, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
    google.golang.org/grpc.(*Server).handleStream(0xc0005f4400, {0x171e5e0, 0xc0001f0f00}, 0xc000028000)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 56
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

    error: preview failed

  nomad:index:Job (nomad-job):
    error: Preview failed: error reading from server: EOF
```

### Affected Resource(s)

nomad.Job

### Output of `pulumi about`

```
CLI          
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown
resource  nomad   2.3.0

Host     
OS       nixos
Version  24.11 (Vicuna)
Arch     x86_64

This project is written in nodejs: executable='/home/demivan/.nix-profile/bin/node' version='v22.4.1'

Current Stack: demivan/project/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/demivan
User           demivan
Organizations  demivan
Token type     personal
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @Demivan. Thanks for reporting the issue. I have reproduced it locally and we will investigate soon.

**Comment by iwahbe** [comment]
Following up, we have root caused the problem and have a PR open to fix it. I'm hoping the fix will land early next week.

**Comment by Demivan** [comment]
@iwahbe Looks like https://github.com/pulumi/pulumi-terraform-bridge/pull/2316 is not the correct fix. In the bot comment https://github.com/pulumi/pulumi-nomad/pull/400#issuecomment-2293648466 it says:
```
🟡 "nomad:index/JobHcl2:JobHcl2": properties: "vars": additional properties type changed from "pulumi.json#/Any" to "string"
```
I have checked the code changes. The change in `sdk/nodejs/types/input.ts` line 369 would prevent passing numbers and other supported types to the job instead of fixing their handling.

**Comment by iwahbe** [comment]
Hi @Demivan. This provider is "bridged" from [terraform-provider-nomad](https://github.com/hashicorp/terraform-provider-nomad), so we inherit the set of supported types from terraform-provider-nomad. The upstream provider exposes `hcl2.vars` as a `{[key: string]: pulumi.Input<string>}`, not as a `{[key: string]: pulumi.Input<any>}`. That's why we saw the crash when passing non-string variables.

https://github.com/pulumi/pulumi-terraform-bridge/pull/2316 is the correct fix, since it brings the set of types we claim to support in line with the set of types we actually support.

**Comment by Demivan** [comment]
Strange, passing numbers and complex types worked with Terraform. But in the provider docs I see:

> Due to the way resource attributes are stored in the Terraform state, the values must be provided as strings.

So, my bad, I was using Terraform provider incorrectly. Looks like Terraform did the conversion for me.

I will try to do a conversion to strings manually with Pulumi. Thanks for your explanation.
